# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lukas.fyi
author: Lukas Klingsbo
author_link: http://lukas.fyi
author_description: Coder, climber and bit crazier than you are allowed to be.
email: lukas.klingsbo@gmail.com
description: Mostly about programming, written by Lukas Klingsbo. Tech that often
    will be mentioned is linux, scala, android and just general hacks.
baseurl: "/blog" # "" the subpath of your site, e.g. /blog
url: "http://lukas.fyi" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: true

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id:

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
